# Generated by Django 5.2.3 on 2025-06-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_name',
            new_name='document_title',
        ),
    ]
