# Generated by Django 5.2.1 on 2025-06-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0002_rename_document_name_document_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
