# Generated by Django 5.2.4 on 2025-08-03 20:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0007_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_type',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
