# Generated by Django 5.2.4 on 2025-08-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0008_remove_document_file_type_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
