# Generated by Django 5.2.5 on 2025-08-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0009_document_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.URLField(),
        ),
    ]
